### ISSUE TITLE
Convert durable entity to new class format

### ISSUE THREAD

**Issue by reisenberger** [Polly-Contrib/Polly.Contrib.AzureFunctions.CircuitBreaker#2]
[Durable Task extension 2.0.0-beta2 release](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.DurableTask/2.0.0-beta2) has a new class-based approach to expressing operations on and property state of entities - more concise and makes calls strongly-typed.

We should simplify [`DurableCircuitBreakerEntity`](https://github.com/Polly-Contrib/Polly.Contrib.AzureFunctions.CircuitBreaker/blob/master/Polly.Contrib.AzureFunctions/CircuitBreaker/DurableCircuitBreakerEntity.cs) (and associated calls into it) to that approach.

Reference: https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-preview#net-programing-models for more information.

**Comment by joelhulen** [comment]
I'll take this one on.

**Comment by reisenberger** [comment]
@joelhulen I have a talk on durable entities in November, and fixed this up as part of that. Just pushed and merged the changes now.
